// examples/react-sdk/ContactForm.jsx
import { useEffect, useRef, useState } from "react";
import { registerContactFormTool } from "webmcp-jp";

export function ContactForm() {
  const [values, setValues] = useState({ name: "", message: "", consent: false });
  const valuesRef = useRef(values);
  const submittedRef = useRef(false);
  valuesRef.current = values;

  useEffect(() => {
    let registration;
    void registerContactFormTool({
      modelContext: document.modelContext,
      read: () => valuesRef.current,
      write: setValues,
      isSubmitted: () => submittedRef.current,
    }).then((result) => {
      registration = result;
    });
    return () => registration?.unregister();
  }, []);

  // humanSubmit は通常UIの onSubmit からだけ呼ぶ。
  const humanSubmit = (event) => {
    event.preventDefault();
    if (submittedRef.current) return;
    submittedRef.current = true;
  };

  return (
    <form onSubmit={humanSubmit}>
      <input value={values.name} onChange={(e) => setValues({ ...values, name: e.target.value })} />
      <textarea value={values.message} onChange={(e) => setValues({ ...values, message: e.target.value })} />
      <button type="submit">人が確認して送信</button>
    </form>
  );
}

// examples/vue-sdk/ContactForm.vue
<script setup>
import { onBeforeUnmount, onMounted, reactive } from "vue";
import { registerContactFormTool } from "webmcp-jp";

const values = reactive({ name: "", message: "", consent: false });
let submitted = false;
let registration;

onMounted(async () => {
  registration = await registerContactFormTool({
    modelContext: document.modelContext,
    read: () => ({ ...values }),
    write: (next) => Object.assign(values, next),
    isSubmitted: () => submitted,
  });
});
onBeforeUnmount(() => registration?.unregister());

// humanSubmit は人が通常UIを送信した場合だけ呼ばれる。
function humanSubmit() {
  if (submitted) return;
  submitted = true;
}
</script>

<template>
  <form @submit.prevent="humanSubmit">
    <input v-model="values.name" />
    <textarea v-model="values.message" />
    <button type="submit">人が確認して送信</button>
  </form>
</template>
